### ISSUE TITLE
iat has expired

### ISSUE THREAD

**Issue by Kirill-Tarasov** [AndrewLt/pyBitZlatoAPI#1]
При отправке запроса получаю ответ от сервера: {'error': 'Unauthorized', 'message': 'An error occurred while attempting to decode the Jwt: iat has expired'}. В чем может быть проблема?

**Comment by AndrewLt** [comment]
К сожалению, не видел вашего сообщения.
В целом эта ошибка относиться к ключу. Ключ может быть неправильно создан, не активирован или просто не правильно вписан при создании класса.
Я обновил недавно файл, там убрана последняя ошибка.
